name: Retrain Model

on:
  push:
    branches:
      - master # or your default branch name

  # schedule:
    # - cron: '0 3 * * 1'  # every Monday at 3am UTC
    #  Use crontab.guru to customize timings.
jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # use your version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow scikit-learn joblib  # just in case

    - name: Run training script
      run: python src/train.py
    - name: Promote Model if RMSE is good
      run: python src/promote_model.py

# email notification
    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ Model Retrained & Promoted to Production"
        to: ${{ secrets.EMAIL_TO }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Hello Akalya,

          Your model has been retrained and successfully promoted to the Production stage in MLflow.

          🎯 Keep up the great work!

          - Your GitHub Actions Workflow 💻


      


    # - name: Upload logs/artifacts (optional)
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: training-logs
    #     path: mlruns/

    # - name: Upload trained model
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: trained-model
    #     path: src/housing_model.pkl 
