name: Retrain Model

on:
  push:
    branches:
      - master  # your default branch
  # schedule:
  #   - cron: '0 3 * * 1'  # every Monday at 3am UTC

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow scikit-learn joblib fairlearn pytest

    - name: Run training script
      run: python src/train.py

    - name: Save run_id.txt as artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: run-id
        path: run_id.txt

    - name: Download run_id.txt
      uses: actions/download-artifact@v3
      with:
        name: run-id

    - name: Register model to MLflow
      run: python src/register_model.py

    - name: Run Tests
      run: pytest test/

    - name: Promote Model if RMSE is good
      run: python src/promote_model.py

    - name: Send Email Notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        secure: true
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: "✅ Model Retrained & Promoted to Production"
        to: ${{ secrets.EMAIL_TO }}
        from: ${{ secrets.EMAIL_USERNAME }}
        body: |
          Hello Akalya,

          Your model has been retrained and successfully promoted to the Production stage in MLflow.

          🎯 Keep up the great work!

          - Your GitHub Actions Workflow 💻

    # Optional: upload trained model if needed
    - name: Upload trained model
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: src/housing_model.pkl
